Migration
OHDSI/SelfControlledCaseSeries pull request #46
Opened 2023-09-07 04:50 UTC by schuemie

This implements migration to the new results data model.

Currently requiring SqlRender 1.16.0, which hasn't been released yet, for the support of `ALTER TABLE ... ADD ...`

The final (migrated) database schema will have four fields (`outcome_rate`_ `adjusted_rate`, `stable`, and `p`) in the `time_trend` table that are not in the CSV files produced by `exportToCsv()` nor in the CSV file describing the results schema. These are deprecated, and are only there so we don't throw away information.

2023-09-07 16:01 UTC, azimov requested changes
The only really important change is the version number in the UpdateVersion.sql - which is very optional and is just something added to CohortDiagnostics.

2023-09-08 03:02 UTC, schuemie commented on inst/sql/UpdateVersionNumber.sql
> +{DEFAULT @version_number = '3.2.3'}
But this is just the default value for SqlRender. The preferred way would be to set the `@version_number` parameter when calling `SqlRender::render()` (which I was assuming is what happened). I'm not sure why you would modify the SQL file itself. That is exactly what SqlRender is for, right?

I added default values to SqlRender just for debugging, not to actually use them in production.

2023-09-08 03:06 UTC, schuemie commented on inst/sql/CreateResultsDataModel.sql
> +  	 analysis_id INT NOT NULL,
Yes, this SQL is completely generated by `ResultModelManager::generateSqlSchema` using the original CSV file here: https://github.com/OHDSI/SelfControlledCaseSeries/blob/v4.2.0/inst/csv/resultsDataModelSpecification.csv . Let me try to regenerate and see if I can find our what is happening.

2023-09-08 03:19 UTC, schuemie commented on inst/sql/CreateResultsDataModel.sql
> +  	 analysis_id INT NOT NULL,
Found the problem: I'm using 'Yes' and 'No', but `generateSqlSchema()` is looking for 'yes' and 'no' (notice the case). May want to make that case insensitive.

2023-09-18 16:34 UTC, azimov approved these changes

2023-09-20 08:23 UTC, merged